config/routes.rb
Rails.application.routes.draw do

  root 'account_sessions#new'

  resources :accounts do
    resources :confirmations, only: [:new, :create]
    resources :schedules
    resources :messages, only: [:new, :create, :index, :show] do
      post 'send_message'
    end
  end
  resources :account_sessions, only: %i(new create destroy)
  get 'login' => 'account_sessions#new', :as => :login
  post 'logout' => 'account_sessions#destroy', :as => :logout

  post '/sms' => 'schedules#receive'

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_many :messages
  belongs_to :account

  def self.send_reminders
    schedules = Schedule.all
    schedules.each do |schedule|

      if Time.now.utc.min == schedule.schedule_time.utc.min

        Message.send_message(schedule.account.phone, schedule.create_primary_template, schedule.id)

      end
      # schedule.messages.each do |message|
      #   diff = Time.now.min.to_i - message.created_at.min.to_i
      #   if message && message.status == 'delivered' && schedule && diff >= 1 && diff < 2
      #     Message.send_message(message.account.phone, schedule.create_primary_rescue, schedule.id)
      #   end
      # end
    end

  end

  def self.send_primary_rescue
    # messages = Message.where("created_at >= ?", Time.zone.now.beginning_of_day-1)
    # messages.each do |message|
    #   schedule = Schedule.find(message.schedule_id)
    #   if message.status == 'delivered' && schedule
    #     #  && (Time.now.hour.to_i - message.created_at.hour.to_i) >= 1
    #     Message.send_message(message.account.phone, schedule.create_primary_rescue, schedule.id)
    #   end
    # end
    # Message.update_old_messages


    Schedule.all.each do |schedule|
      sc_time = schedule.schedule_time.utc.min
      schedule.messages.each do |message|
        diff = Time.now.min.to_i - message.created_at.min.to_i
        ms_time = message.created_at.utc.min
        if message && schedule && ms_time == sc_time && message.status == "delivered" && diff >= 1 && diff < 2
          Message.send_message(message.account.phone, schedule.create_primary_rescue, schedule.id)
          message.update(status: "no_reply")
        end
      end
    end
    # schedule = Schedule.find(message.schedule_id)
    # diff = Time.now.min.to_i - message.created_at.min.to_i


  end

  def self.send_secondary_message
    # messages = Message.where("created_at >= ?", Time.now.utc.beginning_of_day-1)
    # messages.each do |message|
    #   schedule = Schedule.find(message.schedule_id)
    #   if message.status == 'delivered' && (Time.now.min.to_i - message.created_at.min.to_i) >= 2 && schedule
    #     Message.send_message(message.account.secondary_phone, schedule.create_secondary_template, schedule.id)
    #     # Message.send_message(message.account.phone, create_primary_notification, message.schedule.id)
    #   end
    # end
    # Message.update_old_messages

    # message = Message.where("created_at >= ?", Time.zone.now.beginning_of_day-1).order("created_at DESC").first
    # schedule = Schedule.find(message.schedule_id)
    # diff = Time.now.min.to_i - message.created_at.min.to_i
    # if message && message.status == 'delivered' && schedule && diff >= 2 && diff < 3
    #   Message.send_message(message.account.secondary_phone, schedule.create_secondary_template, schedule.id)
    # end
    Schedule.all.each do |schedule|
      sc_time = schedule.schedule_time.utc.min
      schedule.messages.each do |message|
        diff = Time.now.min.to_i - message.created_at.min.to_i
        ms_time = message.created_at.utc.min
        if message && schedule && ms_time == sc_time && message.status == "no_reply" && diff >= 2 && diff < 3
          last_message = schedule.messages.where("created_at > ? AND status = ?", schedule.schedule_time, "delivered").order("created_at DESC").first
          if last_message
            last_message.update(status: "no_reply")
            Message.send_message(message.account.secondary_phone, schedule.create_secondary_template, schedule.id)
            # Message.send_message(message.account.phone, schedule.create_primary_notification, message.schedule.id)
          end
        end
      end
    end
  end

  def self.send_secondary_rescue
    # Message.update_old_messages
    # messages = Message.where("created_at >= ?", Time.now.utc.beginning_of_day-1)
    # messages.each do |message|
    #   if message.status == 'delivered' && (Time.now.hour.to_i - message.created_at.hour.to_i) >= 1
    #     Message.send_message(message.account.secondary_phone, create_secondary_rescue, message.schedule.id)
    #     Message.send_message(message.account.phone, create_primary_notification, message.schedule.id)
    #   end
    # end
    Schedule.all.each do |schedule|
      sc_time = schedule.schedule_time.utc.min
      schedule.messages.each do |message|
        diff = Time.now.min.to_i - message.created_at.min.to_i
        ms_time = message.created_at.utc.min
        if message && schedule && ms_time == sc_time && message.status == "no_reply" && diff >= 3 && diff < 4
          last_message = schedule.messages.where("created_at > ? AND status = ?", schedule.schedule_time, "delivered").order("created_at DESC").first
          if last_message
            last_message.update(status: "no_reply")
            Message.send_message(message.account.secondary_phone, schedule.create_secondary_rescue, message.schedule.id)
          end
        end
      end
    end
  end

  def self.send_emergency_message
    # Message.update_old_messages
    # messages = Message.where("created_at >= ?", Time.now.utc.beginning_of_day-1)
    # messages.each do |message|
    #   if message.status == 'delivered' && (Time.now.hour.to_i - message.created_at.hour.to_i) >= 1
    #     Message.send_message(message.account.emergency_phone, create_emergency_template, message.schedule.id)
    #     Message.send_message(message.account.phone, create_primary_emergency_notification, message.schedule.id)
    #   end
    # end
    Schedule.all.each do |schedule|
      sc_time = schedule.schedule_time.utc.min
      schedule.messages.each do |message|
        # previous = schedule.messages.where("created_at > ? AND status = ?", schedule.schedule_time.min + 3, "delivered").first
        # if schedule.schedule_time + 4
        diff = Time.now.min.to_i - message.created_at.min.to_i
        ms_time = message.created_at.utc.min
        if message && schedule && ms_time == sc_time && message.status == "no_reply" && diff >= 4 && diff < 5
          last_message = schedule.messages.where("created_at > ? AND status = ?", schedule.schedule_time, "delivered").order("created_at DESC").first
          if last_message
            last_message.update(status: "no_reply")
            Message.send_message(message.account.emergency_phone, schedule.create_emergency_template, message.schedule.id)
            # Message.send_message(message.account.phone, schedule.create_primary_emergency_notification, message.schedule.id)
          end
        end
      end
    end
  end

  def create_primary_template
    body = "Hi there #{self.account.name}. Have you checked up on #{self.account.patient_name} recently? Reply YES to confirm. This is an automated message."
    body
  end

  def create_primary_rescue
    body = "Hello again, #{self.account.name}. We haven't heard back from you. Are you ok? Reply YES to confirm. This is an automated message."
    body
  end

  def create_primary_notification
    body = "Hi #{self.account.name}. Because we haven't heard from you, we messaged #{self.account.secondary_name}. Please contact #{self.account.secondary_name} when you get this. This is an automated message."
    body
  end

  def create_primary_emergency_notification
    body = "Hi there #{self.account.name}. Because we haven't heard from you, or #{self.account.secondary_name}, we've notified #{self.account.emergency_name} that there may be an emergency. Please contact #{self.account.emergency_name} as soon as you get this. This is an automated message."
    body
  end

  def create_secondary_template
    body = "Hi #{self.account.secondary_name}. We haven't heard from #{self.account.name} today. Please check on #{self.account.patient_name}. This is an automated message."
    body
  end

  def create_secondary_rescue
    body = "Hello #{self.account.secondary_name}. We haven't heard back from you. Are you ok? Reply YES to confirm, and check on #{self.account.patient_name} as soon as you can. This is an automated message."
    body
  end

  def create_emergency_template
    body = "EMERGENCY!! Hi #{self.account.emergency_name}. We haven't heard from #{self.account.patient_name}'s caregiver today. Can you check on #{self.account.patient_name} at #{self.account.patient_address}? Or you can reach them at #{self.account.patient_number}. In case of an emergency please call 911. This is an automated message."
    body
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def receive
    # find the last message sent to the number
    @relevant_message = Message.where("to_number = ? AND status = ?", params[:From], "delivered").order("created_at DESC").first

    if @relevant_message
      @schedule = Schedule.find(@relevant_message.schedule_id)
      Message.receive_message(params, @relevant_message, @schedule)
      head :ok, content_type: "text/html"
    else
      @message = Message.where("to_number = ?", params[:From]).order("created_at DESC").first
      Message.create({
          body: params[:Body],
          to_number: params[:To],
          from_number: params[:From],
          status: 'received',
          schedule_id: @message.schedule_id
      })
      # alert("wrong reception!!")
    end
  end

  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @account = Account.find(params[:account_id])
    @schedule = Schedule.find(params[:id])
    @incoming_messages = Message.where("schedule_id = ? AND status = ?", @schedule.id, "received")
    @notyet_messages = Message.where("schedule_id = ? AND status = ?", @schedule.id, "delivered")
    @answered_messages = Message.where("schedule_id = ? AND status = ?", @schedule.id, "replied")
    @not_messages = Message.where("schedule_id = ? AND status = ?", @schedule.id, "no_reply")

  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.account_id = params[:account_id]

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to account_schedule_path(params[:account_id], @schedule.id), notice: 'Schedule was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to account_path, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def perform
    Schedule.send_reminders
    Schedule.send_primary_rescue
    Schedule.send_secondary_message
    Schedule.send_secondary_rescue
    Schedule.send_emergency_message
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:schedule_time, :account_id, :id)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for([:account, @schedule]) do |f| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :schedule_time, "When would you like us to check in?" %>
    <%= f.time_select :schedule_time, discard_minute: true, ampm: true %><br>
    <%= f.hidden_field :account_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/_schedule.html.erb
<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% schedules.each do |schedule| %>
      <tr>
        <td><strong><%= "#{schedule.schedule_time.strftime("%l%p")}" %></strong></td>
        <td><%= link_to "Show", account_schedule_path(@account.id, schedule.id) %></td>
        <td><%= link_to 'Edit', edit_account_schedule_path(@account.id, schedule.id) %></td>
        <td><%= link_to 'Destroy', account_schedule_path(@account.id, schedule.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<% if current_user && current_user.id == @schedule.account.id %>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', account_schedule_path %> |
<%= link_to 'Back', account_schedules_path %>
<% elsif current_user %>
<%= link_to "Go to your account", account_path(current_user) %>
<% else %>
<% end %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<% if current_user && current_user.id.to_s == params[:account_id] %>


<%= render 'form', schedule: @schedule %>

<% elsif current_user %>
<%= link_to "Go to your account", account_path(current_user) %>
<% else %>
<% end %>

app/views/schedules/show.html.erb
<% if current_user && current_user.id == @account.id %>


  <strong>Patient Name:</strong> <%= @schedule.account.patient_name %><br>
  <strong>Frequency:</strong> <%= @schedule.frequency_hours %><br>
  <strong>Primary Phone:</strong> <%= number_to_phone(@schedule.account.phone.to_i) %><br>
  <br>

  <p id="notice"><%= notice %></p>
  <p>This scheduled notification started at <%= @schedule.schedule_time.utc.to_formatted_s(:long_ordinal) %></p>
  <p>with a frequency of <em><%= @schedule.frequency_hours %></em> hours.</p>
  <p class="footer"><%= link_to 'Edit', edit_account_schedule_path(@account.id, @schedule.id) %> | <%= link_to 'Back', account_path(@account.id) %></p>


  <h2>Messages regarding this scheduled notification</h2>

  <div class="trigger_container">
    <h4 class="trigger">Incoming messages</h4>

    <div class="messages">

      <% @incoming_messages.each do |message| %>
      <div class="message">
        <p>
          This message was sent by
          <%= message.from_number == message.account.phone ? message.account.name : (message.from_number == message.account.secondary_phone ? message.account.secondary_name : message.account.emergency_name) %>
        </p>
        <p><em><%= message.body %></em></p>
      </div>
      <% end%>
    </div>
  </div>

  <div class="trigger_container">
    <h4 class="trigger">Sent but not (yet) answered messages</h4>

    <div class="messages">

      <% @notyet_messages.each do |message| %>
      <div class="message">
        <p>
          This message was sent to
          <%= message.to_number == message.account.phone ? message.account.name : (message.to_number == message.account.secondary_phone ? message.account.secondary_name : message.account.emergency_name) %>
          and has not been answered (yet).
        </p>
        <p><em><%= message.body %></em></p>
      </div>
      <% end%>
    </div>
  </div>

  <div class="trigger_container">
    <h4 class="trigger">Unanswered messages</h4>

    <div class="messages">
      <% @not_messages.each do |message| %>
      <div class="message">
        <p>
          This message was sent to
          <%= message.to_number == message.account.phone ? message.account.name : (message.to_number == message.account.secondary_phone ? message.account.secondary_name : message.account.emergency_name) %>
          and has not been answered.
        </p>
        <p><em><%= message.body %></em></p>
      </div>
      <% end%>
    </div>
  </div>

  <div class="trigger_container">
    <h4 class="trigger">Sent and answered messages</h4>

    <div class="messages">

      <% @answered_messages.each do |message| %>
      <div class="message">
        <p>
          This message was sent to
          <%= message.to_number == message.account.phone ? message.account.name : (message.to_number == message.account.secondary_phone ? message.account.secondary_name : message.account.emergency_name) %>
          .
        </p>
        <p><em><%= message.body %></em></p>
      </div>
      <% end%>
    </div>
  </div>
<% elsif current_user %>
  <%= link_to "Go to your account", account_path(current_user) %>
<% else %>
<% end %>