config/routes.rb
Rails.application.routes.draw do

  root 'account_sessions#new'

  resources :accounts do
    resources :confirmations, only: [:new, :create]
    resources :schedules
    resources :messages, only: [:new, :create, :index, :show] do
      post 'send_message'
    end
  end
  resources :account_sessions, only: %i(new create destroy)
  get 'login' => 'account_sessions#new', :as => :login
  post 'logout' => 'account_sessions#destroy', :as => :logout

  post '/sms' => 'schedules#receive'

end

app/controllers/account_sessions_controller.rb
class AccountSessionsController < ApplicationController


  def new

    if current_user
      redirect_to account_path(current_user.id)
    else
      # if request.original_url == root_url
      #   hide = true
      # else
      #   hide = false
      # end
      @hide = true
      @account = Account.new
  end
  end

  def create
    if @account = login(params[:email], params[:password])
      redirect_back_or_to(account_path(@account.id))
    else
      flash.now[:alert] = 'Unsuccessful login'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path)
  end
end

app/helpers/account_sessions_helper.rb
module AccountSessionsHelper
end

app/views/account_sessions/_form.html.erb
<%= form_tag account_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email, "E-mail address" %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password, "Password" %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Log In" %>
  </div>
<% end %>

app/views/account_sessions/new.html.erb
<div class="container">

  <%= image_tag 'logo_white', id: 'homepage-logo' %>
  <h2 id="headline">The simpliest emergency fallback system for caregivers.</h2>

  <% flash.each do |key, message| %>
 <div id="alert!" class="flash-<%= key %>"><%= message %></div>
 <% end %>
 <%= render 'form' %>
</div>