config/routes.rb
Rails.application.routes.draw do

  root 'account_sessions#new'

  resources :accounts do
    resources :confirmations, only: [:new, :create]
    resources :schedules
    resources :messages, only: [:new, :create, :index, :show] do
      post 'send_message'
    end
  end
  resources :account_sessions, only: %i(new create destroy)
  get 'login' => 'account_sessions#new', :as => :login
  post 'logout' => 'account_sessions#destroy', :as => :logout

  post '/sms' => 'schedules#receive'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memini</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">
  </head>

  <body>
    <header>
      <nav class="navbar">
          <div class="logo-wrapper">
          <% if current_user %>
            <% unless @hide = false %>
            <%= link_to image_tag('logo_white', id: "logo"), account_path(current_user), class: "head-link" %>
          <% else %>
            <%= link_to image_tag('logo', id: "logo"), root_path, class: "head-link"%>
            <% end %>
          <% end %>
          </div>

        <ul class="navlist">
          <% if current_user %>
            <%= link_to "My Account", account_path(current_user.id) %>
            <%= link_to "Sign Out", :logout, method: :post %>
          <% else %>
            <%= link_to "Log In", new_account_session_path %>
            <%= link_to "Sign Up", new_account_path %>
          <% end %>
          </ul>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>