config/routes.rb
Rails.application.routes.draw do

  root 'account_sessions#new'

  resources :accounts do
    resources :confirmations, only: [:new, :create]
    resources :schedules
    resources :messages, only: [:new, :create, :index, :show] do
      post 'send_message'
    end
  end
  resources :account_sessions, only: %i(new create destroy)
  get 'login' => 'account_sessions#new', :as => :login
  post 'logout' => 'account_sessions#destroy', :as => :logout

  post '/sms' => 'schedules#receive'

end

app/models/account.rb
class Account < ApplicationRecord
  authenticates_with_sorcery!
  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }
  has_many :messages, through: :schedules
  has_many :schedules

  #generates random number for account verification process
  def self.generate
    rand(100000..999999).to_s
  end

  def self.send_confirmation_to(account)
    verification = self.generate
    account.update(verification: verification)
    Message.send_code(account, verification)
  end



end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :verify, exclude: [:new, :create]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

      if @account.save
        session[:account_id] = @account.id
        Account.send_confirmation_to(@account)
        redirect_to new_account_confirmation_path(@account), notice: 'Please verify your phone number.'
        login(params[:account][:email], params[:account][:password])
      else
        render :new
      end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|

      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    def verify
      @account = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name,
                                      :phone,
                                      :email,
                                      :password,
                                      :password_confirmation,
                                      :phone,
                                      :secondary_name,
                                      :secondary_phone,
                                      :secondary_email,
                                      :emergency_name,
                                      :emergency_phone,
                                      :patient_name,
                                      :patient_number,
                                      :patient_address,
                                      :patient_notes)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_blocksetup.html.erb
<%= form_for(account) do |f| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="caregivers">
        <h2>Secondary Caregiver Info</h2>
        <div class="field">
            <%= f.label :secondary_name, "Secondary Caregiver's Name" %><br>
            <%= f.text_field :secondary_name, placeholder: "eg. Johnny Black" %>
        </div>
        <div class="field">
            <%= f.label :secondary_phone, "Secondary Caregiver's Phone" %><br>
            <%= f.text_field :secondary_phone, placeholder: "416-555-1234" %>
        </div>
        <div class="field">
            <%= f.label :emergency_name, "Emergency Caregiver's Name" %><br>
            <%= f.text_field :emergency_name, placeholder: "eg. Jane White" %>
        </div>
        <div class="field">
            <%= f.label :emergency_phone, "Secondary Caregiver's Phone" %><br>
            <%= f.text_field :emergency_phone, placeholder: "416-555-1234" %>
        </div>
    </div>

<div class="patient">
    <h2>Patient info</h2>
    <div class="field">
        <%= f.label :patient_name, "Patient's Name" %><br>
        <%= f.text_field :patient_name, placeholder: "eg. Johnny Black" %>
    </div>
    <div class="field">
        <%= f.label :patient_number, "Patient's Phone Number" %><br>
        <%= f.text_field :patient_number, placeholder: "eg. +12345678910" %>
    </div>
    <div class="field">
        <%= f.label :patient_address, "Patient's Home Address" %><br>
        <%= f.text_field :patient_address, placeholder: "eg. 101 College st, apt. 203" %>
    </div>
    <div class="field">
        <%= f.label :patient_notes, "Patient Notes (Information to send to caregivers in case of emergency)" %><br>
        <%= f.text_area :patient_notes, placeholder: "eg. the extra key is under the flowerpot!" %>
    </div>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/accounts/_form.html.erb
<%= form_for(account) do |f| %>
 <% if account.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>
     <ul>
     <% account.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>
 <div class="caregivers">
   <br>
   <h2>-Your Information-</h2>
   <div class="field">
     <%= f.label :name, "Name" %><br>
     <%= f.text_field :name, placeholder: "eg. Queen Elizabeth II" %>
   </div>
   <div class="field">
     <%= f.label :phone, "Phone Number" %><br>
     <%= f.text_field :phone, placeholder: "eg. +12345678910", required: true %>
   </div>
   <div class="field">
     <%= f.label :email, "Email address" %><br>
     <%= f.text_field :email, placeholder: "eg. ex@mp.le", required: true %>
   </div>
   <div class="field">
     <%= f.label :password, "Password" %><br>
     <%= f.password_field :password, required: true %>
   </div>
   <p class="secondary-next">Next >></p>
 </div>
</div>

</div>
 <div class="secondary-caregiver">
   <h2>Secondary Caregiver Info</h2>
   <div class="field">
     <%= f.label :secondary_name, "Secondary Caregiver's Name" %><br>
     <%= f.text_field :secondary_name, placeholder: "eg. Johnny Black" %>
   </div>
   <div class="field">
     <%= f.label :secondary_phone, "Secondary Caregiver's Phone" %><br>
     <%= f.text_field :secondary_phone, placeholder: "416-555-1234" %>
   </div>
   <div class="emergency-contact">
     <div class="field">
       <%= f.label :emergency_name, "Emergency Caregiver's Name" %><br>
       <%= f.text_field :emergency_name, placeholder: "eg. Jane White" %>
     </div>
     <div class="field">
       <%= f.label :emergency_phone, "Emergency Contact's Phone" %><br>
       <%= f.text_field :emergency_phone, placeholder: "416-555-1234" %>
     </div>
   </div>
   <p class="emerge-next">Next >></p>
   <p class="third-back"><< Back</p>
 </div>
 <div class="patient">
   <h2>Patient info</h2>
   <div class="field">
     <%= f.label :patient_name, "Patient's Name" %><br>
     <%= f.text_field :patient_name, placeholder: "eg. Johnny Black" %>
   </div>
   <div class="field">
     <%= f.label :patient_number, "Patient's Phone Number" %><br>
     <%= f.text_field :patient_number, placeholder: "eg. +12345678910" %>
   </div>
   <div class="field">
     <%= f.label :patient_address, "Patient's Home Address" %><br>
     <%= f.text_field :patient_address, placeholder: "eg. 101 College st, apt. 203" %>
   </div>
   <div class="field">
     <%= f.label :patient_notes, "Patient Notes (Information to send to caregivers in case of emergency)" %><br>
     <%= f.text_area :patient_notes, placeholder: "eg. the extra key is under the flowerpot!" %>
   </div>
     <p class="fourth-back"><< Back</p>
   <%= f.submit %>
 </div>
<% end %>

app/views/accounts/_setup.html.erb
<%= form_for(account) do |f| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="caregivers">
        <h2>Secondary Caregiver Info</h2>
        <div class="field">
            <%= f.label :secondary_name, "Secondary Caregiver's Name" %><br>
            <%= f.text_field :secondary_name, placeholder: "eg. Johnny Black" %>
        </div>
        <div class="field">
            <%= f.label :secondary_phone, "Secondary Caregiver's Phone" %><br>
            <%= f.text_field :secondary_phone, placeholder: "416-555-1234" %>
        </div>
        <div class="field">
            <%= f.label :emergency_name, "Emergency Caregiver's Name" %><br>
            <%= f.text_field :emergency_name, placeholder: "eg. Jane White" %>
        </div>
        <div class="field">
            <%= f.label :emergency_phone, "Secondary Caregiver's Phone" %><br>
            <%= f.text_field :emergency_phone, placeholder: "416-555-1234" %>
        </div>
    </div>

<div class="patient">
    <h2>Patient info</h2>
    <div class="field">
        <%= f.label :patient_name, "Patient's Name" %><br>
        <%= f.text_field :patient_name, placeholder: "eg. Johnny Black" %>
    </div>
    <div class="field">
        <%= f.label :patient_number, "Patient's Phone Number" %><br>
        <%= f.text_field :patient_number, placeholder: "eg. +12345678910" %>
    </div>
    <div class="field">
        <%= f.label :patient_address, "Patient's Home Address" %><br>
        <%= f.text_field :patient_address, placeholder: "eg. 101 College st, apt. 203" %>
    </div>
    <div class="field">
        <%= f.label :patient_notes, "Patient Notes (Information to send to caregivers in case of emergency)" %><br>
        <%= f.text_area :patient_notes, placeholder: "eg. the extra key is under the flowerpot!" %>
    </div>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Your Account</h1>

<p class="prime"><strong>STEP 1</strong></br> Edit Primary Contact (Your information)</p>
<p class="secondary"><strong>STEP 2</strong></br>Edit Secondary Contact</p>
<p class="emerge"><strong>STEP 3</strong></br>Edit Patient Info</p>

<%= render 'form', account: @account %>


<%= link_to 'Show', @account %> | <%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %> -->

app/views/accounts/new.html.erb
<h1>New Account</h1>
</br></br>
<%= render 'form', account: @account %>

app/views/accounts/show.html.erb
<% if current_user && current_user.id == @account.id %>
<p id="notice"><%= notice %></p>
<div class="account-details">
  <h2>Account Details</h2>
  <p><strong>Patient name:</strong> <%= @account.patient_name %></p>
  <p><strong>Patient phone number:</strong> <%= number_to_phone(@account.patient_number.to_i) %></p>
  <p><strong>Patient address:</strong> <%= @account.patient_address %></p>
  <p><strong>Patient notes:</strong> <%= @account.patient_notes %></p>
  <p><strong>Primary caregiver:</strong> <%= @account.name %></p>
  <p><strong>Primary phone:</strong><%= number_to_phone(@account.phone.to_i) %></p>
  <p><strong>Secondary caregiver:</strong> <%= @account.secondary_name %></p>
  <p><strong>Secondary phone:</strong> <%= number_to_phone(@account.secondary_phone.to_i) %></p>
  <p><strong>Emergency caregiver:</strong> <%= @account.emergency_name %></p>
  <p><strong>Emergency phone:</strong> <%= number_to_phone(@account.emergency_phone.to_i) %><p>
  <%= link_to 'Edit', edit_account_path(@account) %> |
  <%= link_to 'Back', accounts_path %>
</div>
<div class="schedule">
<h2>Schedules</h2>
  <%= link_to "Create a new schedule", new_account_schedule_path(current_user) %>
  <%= render '/schedules/schedule', schedules: @account.schedules %>
<% elsif current_user %>
  <%= link_to "Go to your account", account_path(current_user) %>
<% else %>
<% end %>
</div>